service: aws-node-auction-service
frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: us-east-1
  profile: serverless-admin
  stage: ${opt:stage, 'dev'}
  
functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello
